### ISSUE TITLE
Question: Is this prone to hitting limits like triggers do?

### ISSUE THREAD

**Issue by studious** [Pixel-Meister/ApexWebhook#1]
Hi Justin.

I've spent days trying to understand how to properly manage limits. I have an endpoint that was connected to another Salesforce org and after migration the webhooks stopped firing. I was going to iterate over a trigger based insert/update list (Trigger.new) with a callout per object, but then I found that triggers must assume 200 records in Trigger.new but they can only make 100 future callouts, which ruins that approach.

Does your flow invoked invocableMethod side step these "bulk" limits that triggers have? I see your code is also iterating over the list with a webhook callout per object. I've wired your code up to a flow and it reaches my endpoint but I still need clarity on the limits.

Regards

**Comment by Pixel-Meister** [comment]
It's all still subject to governor limits, but since this isn't a trigger it falls under [different limits](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_invoking_future_methods.htm). I'm not 100% sure though.

You could test it by changing the test class to make 101 input SObjects and seeing if it hits governor limits?
Made this test in GPT-3 so take it with a grain of salt. Looks like it should work though.
`@isTest
public class TestWebookCallout {
    @isTest static void testIdList() {
        List<SObject> cruella= new List<SObject>();
        for (Integer i = 0; i < 101; i++) {
            SObject dalmation= new Contact(
                Email = 'name' + i.toString() + '@email.org',
                FirstName = 'first' + i.toString(),
                LastName = 'last' + i.toString()
            );
            cruella.add(dalmation);
        }
        WebhookCallout.webhookCalloutInputs testCalloutOne = new WebhookCallout.webhookCalloutInputs();
        testCalloutOne.inputObject = cruella;
        testCalloutOne.endpoint = 'exampleendpoint.com';
        List<WebhookCallout.webhookCalloutInputs> listInputs = new List<WebhookCallout.webhookCalloutInputs>();
        listInputs.add(testCalloutOne);
        test.startTest();
    WebhookCallout.postRequest(listInputs);
        Test.stopTest();`

**Comment by Pixel-Meister** [comment]
Actually, it looks like if you go over 200 calls it also errors as well. So it is prone to hitting those limits.

**Comment by studious** [comment]
Thanks, I couldn't find any answers for how many objects would come through a flow. Trigger limits are very clear, but I couldn't put my finger on the upper range of the list coming through a flow (create/update).

This wouldn't be a problem in our main use case but every now and then our Customer Support staff will create a spreadsheet to change a custom field and import this using a data import. It's this rare occurence I am trying to design for.

I appreciate your response.
